server: 
  port: 80

spring: 
  profiles: dev
#  datasource: 
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/clientdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
#    username: admin
#    password: password
#  jpa: 
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate: 
#      ddl-auto: update
  datasource: 
    url: jdbc:h2:mem:clientdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  jpa: 
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: 
      ddl-auto: update

security: 
  oauth2: 
    client: 
      user-authorization-uri: http://localhost:8081/oauth/authorize
      access-token-uri: http://localhost:8081/oauth/token
    resource: 
      user-info-uri: http://localhost:8082/user/me

logging: 
  path: /var/log/logback
